### PR TITLE
[MEGA PR] Rework DKG async protocol and runtime logs

### LINKED ISSUE #289: [SPEC] Standardizing log output for DKG
# Overview 

Currently we have all kinds of logs, with different formats, used for different reasons. We should outline and document a standard approach to adding logs, their targets, and format. 

## Examples 

# Questions/Issues

### LINKED ISSUE #352: [BUG] Queued DKG has issues on initial execution
**Describe the bug**
Queued DKG never reliably finishes on the first execution in the parachain context.

### LINKED ISSUE #362: [TASK] Investigate every branch that can throw an error and add logs
**Issue summary**
Investigate in the workers/handlers where it is possible for the sub-protocols (Keygen / Signing) to terminate. The main focus being the Keygen, since we are having reliability issues there. Match on the results instead of unwrapping them and add logs into these matchings.

Ideally, we have a checklist of all the areas in which we see logs appear over time, so we can identify a distribution of errors and where they occur.

### PR DESCRIPTION
**Pull request by drewstone**
**Summary of changes**
Changes introduced in this pull request:
- Update the runtime log labels
- Update off-chain logs related to DKG keygen storage and execution
- Add logs to offchain worker functionality in the pallets
- Rework aync DKG Protocol.

Closes #352
Closes #362 
Closes #289

### CODE REVIEW

File: scripts/run-parachain.ts [hunk 1]
```diff
@@ -0,0 +1,292 @@
...
+  WsProvider,
+} from "https://esm.sh/@polkadot/api@9.2.3?bundle";
+import { Input } from "https://deno.land/x/cliffy@v0.24.3/prompt/mod.ts";
+import { assert } from "https://deno.land/std@0.152.0/testing/asserts.ts";
+import {
+  keypress,
+  KeyPressEvent,
+} from "https://deno.land/x/cliffy@v0.24.3/keypress/mod.ts";
+
+type ScrtipState = {
```
Comment (drewstone) [inline scripts/run-parachain.ts:17]: What is this supposed to be @shekohex ? Not sure I understand the naming.

Comment (shekohex) [reply scripts/run-parachain.ts:17]: Oh, I will fix that, it should be `ScriptState`.
